In [82]:
import pandas as pd

In [81]:
df= pd.read_csv(r"C:\Users\anupr\upflair\pandas\project\bike\Used_Bikes.csv")

In [ ]:
df

In [ ]:
df.head() #starting 5 values

In [ ]:
df.tail() #last 5 values

In [ ]:
df.info() #volumns information

In [ ]:
df.bike_name

In [ ]:
df['brand']

In [ ]:
df[['brand']]

In [ ]:
df[['owner']]

In [ ]:
df['brand'].unique()

In [ ]:
df['bike_name'].nunique() #number of unique values

In [ ]:
df['brand'].value_counts()

In [ ]:
df.duplicated() #In pandas, the duplicated() method identifies duplicate rows in a DataFrame or duplicate values in a Series by returning a boolean Series (True for a duplicate, False for unique)

In [ ]:
df.duplicated().sum()

In [41]:
df.drop_duplicates(inplace=True) #drop_duplicates() to find, view, or remove redundant data.
#The drop_duplicates() method in Pandas is designed to remove duplicate rows from a DataFrame based on all columns or specific ones. By default, it scans the entire DataFrame and retains the first occurrence of each row and removes any duplicates that follow.

In [ ]:
df

In [ ]:
df.duplicated().sum()

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df.drop("city",axis=1,inplace=True)

In [ ]:
df

In [ ]:
df.select_dtypes

In [42]:
char=df.select_dtypes(include= 'object')
# num=df.select_dtypes(exclude= 'object')

C:\Users\anupr\AppData\Local\Temp\ipykernel_54672\3044823918.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char=df.select_dtypes(include= 'object')

In [ ]:
char

In [ ]:
num

In [ ]:
char=df.select_dtypes(include= 'O')
num=df.select_dtypes(exclude= 'O')

In [ ]:
char

In [43]:
owner_dict ={'First Owner':1,
             'Second Owner':2,
             'Third Owner':3,
             'Fourth Owner Or More':4}
char['owner']= char['owner'].map(owner_dict)

In [44]:
char

                                 bike_name       city  owner            brand
0       TVS Star City Plus Dual Tone 110cc  Ahmedabad      1              TVS
1              Royal Enfield Classic 350cc      Delhi      1    Royal Enfield
2                     Triumph Daytona 675R      Delhi      1          Triumph
3                     TVS Apache RTR 180cc  Bangalore      1              TVS
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore      1           Yamaha
...                                    ...        ...    ...              ...
9362             Hero Hunk Rear Disc 150cc      Delhi      1             Hero
9369                   Bajaj Avenger 220cc  Bangalore      1            Bajaj
9370        Harley-Davidson Street 750 ABS    Jodhpur      1  Harley-Davidson
9371                 Bajaj Dominar 400 ABS  Hyderabad      1            Bajaj
9372              Bajaj Avenger Street 220  Hyderabad      1            Bajaj

[7324 rows x 4 columns]

In [51]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [52]:
brand_dict={'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23}
char['brand']= char['brand'].map(brand_dict)

In [58]:
char[['brand', 'owner']]

      brand  owner
0         1      1
1         2      1
2         3      1
3         1      1
4         4      1
...     ...    ...
9362      6      1
9369      7      1
9370     15      1
9371      7      1
9372      7      1

[7324 rows x 2 columns]

In [59]:
total_df= pd.concat([char,num], axis=1)

In [60]:
total_df

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,1,1,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,1,2,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,1,3,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,1,1,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,1,4,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,1,6,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,1,7,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,1,15,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,1,7,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,1,7,80000.0,7127.0,5.0,220.0

In [70]:
total_df.duplicated().sum()

np.int64(0)

In [71]:
total_df.drop_duplicates(inplace=True)

In [72]:
total_df.isnull().sum()

bike_name     0
city          0
owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [73]:
total_df.to_csv('clean_bike.csv')

In [75]:
x=total_df.drop('price', axis=1)

In [76]:
x

,bike_name,city,owner,brand,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,1,1,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,1,2,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,1,3,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,1,1,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,1,4,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,1,6,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,1,7,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,1,15,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,1,7,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,1,7,7127.0,5.0,220.0

In [77]:
y=total_df[['price']]

In [78]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [79]:
tvs_df=total_df['brand']=="TVS"

In [80]:
tvs_df

0       False
1       False
2       False
3       False
4       False
        ...
9362    False
9369    False
9370    False
9371    False
9372    False
Name: brand, Length: 7324, dtype: bool