In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\anupr\upflair\pandas\project\bike\Used_Bikes.csv")
char=df.select_dtypes(include="O")
num=df.select_dtypes(exclude="O")

C:\Users\anupr\AppData\Local\Temp\ipykernel_96652\641161924.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char=df.select_dtypes(include="O")

In [3]:
owner_dict={'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}
char['owner']=char['owner'].map(owner_dict)

In [27]:
char[['owner','bike_name']]

       owner                             bike_name
0          1    TVS Star City Plus Dual Tone 110cc
1          1           Royal Enfield Classic 350cc
2          1                  Triumph Daytona 675R
3          1                  TVS Apache RTR 180cc
4          1  Yamaha FZ S V 2.0 150cc-Ltd. Edition
...      ...                                   ...
32643      1                Hero Passion Pro 100cc
32644      1                  TVS Apache RTR 180cc
32645      1              Bajaj Avenger Street 220
32646      1             Hero Super Splendor 125cc
32647      1                    Bajaj Pulsar 150cc

[32648 rows x 2 columns]

In [28]:
totaldf=pd.concat([char,num],axis=1)#used to add column
print(totaldf)

                                  bike_name       city  owner          brand  \
0        TVS Star City Plus Dual Tone 110cc  Ahmedabad      1            TVS
1               Royal Enfield Classic 350cc      Delhi      1  Royal Enfield
2                      Triumph Daytona 675R      Delhi      1        Triumph
3                      TVS Apache RTR 180cc  Bangalore      1            TVS
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore      1         Yamaha
...                                     ...        ...    ...            ...
32643                Hero Passion Pro 100cc      Delhi      1           Hero
32644                  TVS Apache RTR 180cc     Karnal      1            TVS
32645              Bajaj Avenger Street 220      Delhi      1          Bajaj
32646             Hero Super Splendor 125cc     Jaipur      1           Hero
32647                    Bajaj Pulsar 150cc       Pune      1          Bajaj

          price  kms_driven   age  power
0       35000.0     17654.0   3.0  110.0
1      119900.0     11000.0   4.0  350.0
2      600000.0       110.0   8.0  675.0
3       65000.0     16329.0   4.0  180.0
4       80000.0     10000.0   3.0  150.0
...         ...         ...   ...    ...
32643   39000.0     22000.0   4.0  100.0
32644   30000.0      6639.0   9.0  180.0
32645   60000.0     20373.0   6.0  220.0
32646   15600.0     84186.0  16.0  125.0
32647   22000.0     60857.0  13.0  150.0

[32648 rows x 8 columns]

In [29]:
totaldf.duplicated().sum()

np.int64(25324)

In [30]:
totaldf=totaldf.drop_duplicates()

In [31]:
totaldf.duplicated().sum()

np.int64(0)

In [32]:
totaldf.isnull().sum()

bike_name     0
city          0
owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [33]:
totaldf.to_csv("Clean data.csv")

In [34]:
print(totaldf)

                                 bike_name       city  owner            brand  \
0       TVS Star City Plus Dual Tone 110cc  Ahmedabad      1              TVS
1              Royal Enfield Classic 350cc      Delhi      1    Royal Enfield
2                     Triumph Daytona 675R      Delhi      1          Triumph
3                     TVS Apache RTR 180cc  Bangalore      1              TVS
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore      1           Yamaha
...                                    ...        ...    ...              ...
9362             Hero Hunk Rear Disc 150cc      Delhi      1             Hero
9369                   Bajaj Avenger 220cc  Bangalore      1            Bajaj
9370        Harley-Davidson Street 750 ABS    Jodhpur      1  Harley-Davidson
9371                 Bajaj Dominar 400 ABS  Hyderabad      1            Bajaj
9372              Bajaj Avenger Street 220  Hyderabad      1            Bajaj

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 8 columns]

In [35]:
y=(totaldf['price'])
y.to_csv("pricelist.csv")

In [36]:
x=totaldf.drop("price",axis=1)
x

,bike_name,city,owner,brand,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,1,TVS,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,1,Royal Enfield,11000.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,1,Triumph,110.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,1,TVS,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,1,Yamaha,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,1,Hero,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,1,Bajaj,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,1,Harley-Davidson,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,1,Bajaj,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,1,Bajaj,7127.0,5.0,220.0

In [6]:
df=pd.read_csv('Used_Bikes.csv')

In [7]:
brandtvs=df['brand']=="TVS"

In [8]:
brandtvs

0         True
1        False
2        False
3         True
4        False
         ...
32643    False
32644     True
32645    False
32646    False
32647    False
Name: brand, Length: 32648, dtype: bool

In [10]:
tvs_firstowner_df=brandtvs[brandtvs['owner']=='First Owner']

KeyError: 'owner'