In [ ]:
import pandas as pd
# df=pd.read_csv('Used_Bikes.csv')
df=pd.read_csv(r"C:\Users\anupr\upflair\pandas\project\bike\Used_Bikes.csv")
char=df.select_dtypes(include="O")
num=df.select_dtypes(exclude="O")

In [23]:
tvs_df= df[(df['brand']=='TVS')&
           (df['owner']=='First Owner')]

In [24]:
tvs_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [ ]:
tvs_firstowner_df=tvs_df[tvs_df['owner']=='First Owner']

In [ ]:
tvs_firstowner_df

In [22]:
rf_df=df[(df['brand']=='Royal Enfield')& 
         (df['owner']=='First Owner')&
         (df['kms_driven']<=50000)&
         (df['age']<=2)&
         (df['price']<=2000000)]
         
df.query("brand== 'Royal Enfield' and owner== 'First Owner' and kms_driven<=50000 and age<=2 and price<=2000000")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
7706,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [20]:
rf_df

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,First Owner,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
7706,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [35]:

hero_df=df[(df['brand']=='Hero')&
         (df['price']<=70000)&
         (df['owner']=='Second Owner')&
         (df['age']<=3)&
         (df['kms_driven']<=35000)]
         
df.query("brand== 'Hero' and price<=70000 and owner== 'Second Owner' and age<=3 and kms_driven<=35000 ")

,bike_name,price,city,kms_driven,owner,age,power,brand
8176,Hero Glamour Fi 125cc,51000.0,Jobner,15500.0,Second Owner,3.0,125.0,Hero
8898,Hero Glamour Fi 125cc,51000.0,Jobner,15500.0,Second Owner,3.0,125.0,Hero

In [36]:
hero_df

,bike_name,price,city,kms_driven,owner,age,power,brand
8176,Hero Glamour Fi 125cc,51000.0,Jobner,15500.0,Second Owner,3.0,125.0,Hero
8898,Hero Glamour Fi 125cc,51000.0,Jobner,15500.0,Second Owner,3.0,125.0,Hero